# Generated by Django 4.1.7 on 2023-05-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Имя пользователя", max_length=900
                    ),
                ),
                (
                    "email",
                    models.CharField(db_index=True, help_text="E-mail", max_length=200),
                ),
                ("password", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=200)),
                ("profile_pic", models.ImageField(blank=True, upload_to="profile_pic")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        db_index=True, help_text="Имя пользователя", max_length=900
                    ),
                ),
                ("profile_pic", models.ImageField(blank=True, upload_to="profile_pic")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Скан подтверждающего документа",
                        upload_to="products/%Y/%m/%d",
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "products_name",
                    models.ForeignKey(
                        help_text="Курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_name",
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
