# Generated by Django 4.2.1 on 2023-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_school_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, default='NO NAME', help_text='Название школы (образовательной организации)', max_length=900),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Краткое описание курса (опционально).', max_length=77),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
