# Generated by Django 4.2.1 on 2023-05-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_user_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='products_name',
            field=models.ForeignKey(help_text='Курс', on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='shop.product'),
        ),
    ]
