# Generated by Django 4.1.4 on 2023-05-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='courseschool',
            unique_together={('product', 'school')},
        ),
    ]
