# Generated by Django 4.1.4 on 2023-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_basket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='API_Key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
