# Generated by Django 4.1.7 on 2023-05-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_school_available_alter_school_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="slug",
        ),
    ]
