# Generated by Django 4.2.1 on 2023-05-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_school_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='info',
            field=models.CharField(db_index=True, help_text='Информация о школе', max_length=900),
        ),
    ]
